//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourExceptionnel
    {
        public System.DateTime DateDebut { get; set; }
        public int DebutRepasId { get; set; }
        public int FinRepasId { get; set; }
        public int Jour { get; set; }
        public bool Ouvert { get; set; }
    
        public virtual Repas Repas { get; set; }
        public virtual Repas Repas1 { get; set; }
    }
}
