//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouverture
    {
        public int JourSemaine { get; set; }
        public int RepasId { get; set; }
        public bool Ouvert { get; set; }
    }
}
