//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlageRepas
    {
        public int JourSemaineId { get; set; }
        public System.TimeSpan Debut { get; set; }
        public System.TimeSpan Fin { get; set; }
        public System.TimeSpan Pas { get; set; }
    }
}
