//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repas()
        {
            this.CreneauRepas = new HashSet<CreneauRepas>();
            this.JourExceptionnel = new HashSet<JourExceptionnel>();
            this.JourExceptionnel1 = new HashSet<JourExceptionnel>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public System.TimeSpan DebutDefaut { get; set; }
        public System.TimeSpan FinDefaut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreneauRepas> CreneauRepas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourExceptionnel> JourExceptionnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourExceptionnel> JourExceptionnel1 { get; set; }
    }
}
