//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLinq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visite
    {
        public int Id { get; set; }
        public string AdresseIp { get; set; }
        public Nullable<System.DateTime> DateTimeVisite { get; set; }
        public string Url { get; set; }
        public Nullable<int> UtilisateurId { get; set; }
        public string UrlOrigine { get; set; }
        public string Navigateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
